baseURL = "https://limubai404.github.io/"
languageCode = "zh-cn"
title = "æˆ‘çš„æŠ€æœ¯åšå®¢"
theme = "PaperMod"

[params]
    defaultTheme = "dark"

    [params.homeInfoParams]
        Title = "æ¬¢è¿ ğŸ‘‹"
        Content = "ä¸ªäººæŠ€æœ¯åˆ†äº«ä»¥åŠæ€»ç»“ï¼"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 10
